version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-chk
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: chk

volumes:
  mongo_data:
